# Generated by Django 3.2.23 on 2023-11-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
