# Generated by Django 3.2.23 on 2023-11-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20231126_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
